<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild><!--在构建时生成包-->
		<Version>3.3.4</Version>
		<Authors>李仕鹏</Authors>
		<Product>Shipeng.Util</Product>
		<PackageReleaseNotes>Zip操作基于DotNetZip的封装增加压缩文件按指定字符串指定截取索引截取文件名称 https://gitee.com/lsp5201314/shipeng-s</PackageReleaseNotes><!--包版本说明-->
		<Copyright>lishipeng</Copyright><!--版权-->
		<Description>LiShiPeng通用辅助工具，包含几乎所有常用工具类，如需详细了解请访问https://gitee.com/lsp5201314/shipeng-s</Description><!--描述-->
		<ReleaseNotes>通用工具类</ReleaseNotes><!--发布说明-->

		<!--在 .NET 生态系统中逐步停用 BinaryFormatter 的过程中，这些方法被标记为“过时”-->
		<!--停止在代码中使用 BinaryFormatter。 此时，考虑使用 JsonSerializer 或 XmlSerializer-->
		<!-- Disable "BinaryFormatter is obsolete" warnings for entire project 在项目文件中取消警告-->
		<!--<NoWarn>$(NoWarn);SYSLIB0011</NoWarn>-->
		<!-- Warning: Setting the following switch is *NOT* recommended in web apps. 若要继续在 ASP.NET 应用中使用 BinaryFormatter，可以在项目文件中重新启用它,非常不建议这样做-->
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Abp.AutoMapper" Version="8.0.0" />
    <PackageReference Include="AspectCore.Abstractions" Version="2.3.0" />
    <PackageReference Include="Aspose.Cells" Version="23.2.0" />
    <PackageReference Include="Aspose.Words" Version="23.2.0" />
    <PackageReference Include="Autofac" Version="6.5.0" />
    <PackageReference Include="Caching.CSRedis" Version="3.8.670" />
    <PackageReference Include="Castle.Core.AsyncInterceptor" Version="2.1.0" />
    <PackageReference Include="ce.office.extension" Version="2.0.0" />
    <PackageReference Include="CSRedisCore" Version="3.8.670" />
    <PackageReference Include="DotNettySocket" Version="1.2.0" />
    <PackageReference Include="DotNetZip" Version="1.16.0" />
    <PackageReference Include="EFCore.Sharding.PostgreSql" Version="7.0.1" />
    <PackageReference Include="EFCore.Sharding.SqlServer" Version="7.0.1" />
    <PackageReference Include="EPPlus" Version="6.1.3" />
    <PackageReference Include="FreeSpire.Office" Version="8.2.0" />
    <PackageReference Include="IdHelper.Zookeeper" Version="1.5.1" />
    <PackageReference Include="JPushSDK" Version="1.0.0" />
    <PackageReference Include="MailKit" Version="3.5.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Html.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="7.0.0" />
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004" />
    <PackageReference Include="Minio" Version="4.0.7" />
    <PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.2.22" />
    <PackageReference Include="mongocsharpdriver" Version="2.19.0" />
    <PackageReference Include="MongoDB.Bson" Version="2.19.0" />
    <PackageReference Include="MongoDB.Driver" Version="2.19.0" />
    <PackageReference Include="MySqlConnector" Version="2.2.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <PackageReference Include="NodaTime" Version="3.1.6" />
    <PackageReference Include="Npgsql" Version="7.0.2" />
    <PackageReference Include="NPOI" Version="2.6.0" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="3.21.90" />
    <PackageReference Include="PinYinConverterCore" Version="1.0.2" />
    <PackageReference Include="QRCoder" Version="1.4.3" />
    <PackageReference Include="Quartz" Version="3.6.2" />
    <PackageReference Include="RabbitMQ.Client" Version="6.4.0" />
    <PackageReference Include="Serenity.Web" Version="3.14.5" />
    <PackageReference Include="ServiceStack.Redis" Version="6.6.0" />
    <PackageReference Include="SharpCompress" Version="0.32.2" />
    <PackageReference Include="SqlSugar.IOC" Version="2.0.0" />
    <PackageReference Include="SqlSugarCore" Version="5.1.3.52" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.2.25" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.10.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="7.0.0" />
    <PackageReference Include="ThoughtWorks.QRCodeCore" Version="1.0.0" />
    <PackageReference Include="ToolGood.Words" Version="3.1.0" />
    <PackageReference Include="ZKWeb.System.Drawing" Version="4.0.1" />
    <PackageReference Include="ZXing.Net.Bindings.ImageSharp.V2" Version="0.16.15" />
    <PackageReference Include="ZXing.Net.Bindings.ZKWeb.System.Drawing" Version="0.16.7" />
  </ItemGroup>

</Project>
