<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PearAdmin.AbpTemplate.Storage\PearAdmin.AbpTemplate.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Abp" Version="7.3.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.1" />
    <PackageReference Include="Minio" Version="4.0.5" />
  </ItemGroup>
  
</Project>
